### ISSUE TITLE
[TO-DO] Prepare for a release

### ISSUE THREAD

**Issue by ii7mood** [ii7mood/LiveMood#1]
- [x] Write a working oAuthreinit() implementation of the TwitchC module [commit](https://github.com/ii7mood/LiveMood/commit/97de58340bd7f646fafd323e0bcb5c0102974dca)
- [x] Add a setup.py that aids the user in setting up an instance of LiveMood (ideally incl API keys etc)  [commit](https://github.com/ii7mood/LiveMood/commit/237073da930e521ca630b1ad35b6c3cbef7e0818)
- [x] Re-write Streamers.py, currently a mess. [commit #1](https://github.com/ii7mood/LiveMood/commit/019b6bb1e99b60432b965987c14cefac3905073f) [commit #2](https://github.com/ii7mood/LiveMood/commit/6c9da506dada44206a7f132657470c5491527931) [commit #3](https://github.com/ii7mood/LiveMood/commit/4284edc7e8577c6226f49f919dfdceb785472ac9)
- [x] Windows support !! (TwitchC.py, Streamers.py, etc) [commit](https://github.com/ii7mood/LiveMood/commit/7e9f6c69e2302ad01b677fab7b157efb2b10aeb3)
- [x] Write a README.md
- [x] Test, test, test, and more tests.
- [ ] (Optionally) Write a Pushover module
- [x] (Optionally) Include a section within the README (or better yet, a wiki) on writing modules/listeners.
- [ ] Add support for member-only streams on both YouTube and Twitch [commit](https://github.com/ii7mood/LiveMood/commit/7bb3b5879eeffc87c195607dae71beb7353dc885) (does not work)

NOTES: ~~member-only streams support has not been tested. No one I currently follow has a scheduled/live stream so I could not attempt it but using a test script with yt-dlp argument cookie passed to it allowed me to download a members-only stream so I assume it works. Will edit this once confirmed. (Question is does appending '/live' to URL redirect to members-only streams?)~~ Appending '/live' to the end of a URL does *not* redirect to a members-only stream, making the the path_to_cookies field completely useless (for now). Will eventually do this though, even if it means writing my own parser of the YouTube '/streams' page.

Update: Plyers' notify(icon_path) has to point at a .ico file to work on Windows. This will be dealt with later, for now I will simply not allow the desktop listener module to work on Windows. Other than that Windows support is pretty much done. Next, I will swap my existing YT/TV notif system to this one for a week and see how it fares.

**Comment by ii7mood** [comment]
Alright, I think the project is now suitable for (a very minimal) release. Just a little cleaning up is needed and we should be good to go.

- [ ] Restructure the code to follow the newly written [project principles](https://github.com/ii7mood/LiveMood/blob/main/project_principles.md)
- [ ] Add displaying examples of the two different listeners available (Discord, Desktop)
